---
apiVersion: v1
data:
  # yamllint disable-line rule:line-length
  replicas-username: cmVwbGljYXMtdXNlcg== # don't change
  replicas-password: UmVwbGljYXMxMjM=
kind: Secret
metadata:
  name: system-acl
type: Opaque
